### ISSUE TITLE
ENUserStoreClient is not accessible

### ISSUE THREAD

**Issue by Thomas-Fleming** [evernote/evernote-cloud-sdk-windows#22]
The `ENUserStoreClient` is instantiated in the `ENSession` class but is private, so not available to consumers of the `ENSession` or `ENSessionAdvanced` objects. This makes it impossible to access the User Store, which the Evernote documentation suggest should be possible.

**Comment by mpnow** [comment]
The Windows client was modeled after the iOS client.  This issue was fixed in the iOS client [here](https://github.com/evernote/evernote-cloud-sdk-ios/commit/18ba5b46ffc06239d3ed880dec913bccb9345055).  The analogous changes could be made to the Windows client to expose UserStore using the Advanced session object.

**Comment by Thomas-Fleming** [comment]
Looks like they just added a property exposing the object. We could make it public on `ENSession`, or internal on `ENSession` and public on `ENSessionAdvanced` which I think is how some other properties currently work. Got a preference?

**Comment by mpnow** [comment]
> internal on ENSession and public on ENSessionAdvanced

I would go that way to keep it consistent with the iOS design.

**Comment by Thomas-Fleming** [comment]
Pull request here: [https://github.com/evernote/evernote-cloud-sdk-windows/pull/23]
